site_name: v3xctrl Wiki
site_url: https://wiki.v3xctrl.com/
repo_url: https://github.com/stylesuxx/v3xctrl
repo_name: stylesuxx/v3xctrl
edit_uri: ""
copyright: Copyright &copy; 2025 v3xctrl

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

hooks:
  - hooks/edit_url.py

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - toc:
      permalink: true
      toc_depth: 3
  - tables

nav:
  - Getting Started:
    - Quickstart: index.md
    - Shopping List: Shopping-List.md
    - Terminology: Terminology.md
    - Motivation: Motivation.md
  - Streamer:
    - Streamer: Streamer.md
    - Pinout: Pinout.md
    - Compatible Hardware: Hardware.md
    - Web Interface: Web-Interface.md
    - Calibration: Calibration.md
    - Tuning Encoder Settings: Tuning-encoder-settings.md
    - Modems: Modems.md
    - SIM: SIM.md
    - Antennas: Antennas.md
    - UART: UART.md
  - Viewer:
    - Viewer: Viewer.md
    - Input Devices: Input-devices.md
    - Controller Setup: Controller-Setup.md
    - Video Receiver Backends: Video-Receiver-Backends.md
  - Networking:
    - Connection Types: Connection-Types.md
    - Network Testing: Network-Testing.md
    - Latency: Latency.md
    - Control Channel: Control-Channel.md
    - Carriers: Carriers.md
  - Troubleshooting:
    - Troubleshooting: Troubleshooting.md
    - FAQ: FAQ.md
    - Known Issues: Known-Issues.md
    - Limitations: Limitations.md
  - Development:
    - Development: Development.md
    - Release: x-Release.md
    - New Release Checklist: x-New-Release-Checklist.md
    - OS Update Checklist: x-OS-Update-Checklist.md
    - OS Benchmarks: x-OS-Benchmarks.md
